{
 "title": "Application",
 "description": "This dashboard displays information used to observe the Flask application.",
 "tags": [
  "flask",
  "application",
  "observability"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Application stats",
   "type": "table",
   "description": "This panel shows information about the application services.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (instance, namespace, container) (kube_pod_container_info{container=~\"backend|frontend\"})"
    },
    {
     "expr": "max by (container) (time() - container_start_time_seconds{container=~\"backend|frontend\"})"
    }
   ]
  },
  {
   "title": "Success Request",
   "type": "timeseries",
   "description": "This panel shows the total number of successful requests per service.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by (container, status) (rate(flask_http_request_duration_seconds_count{container=~\"backend|frontend\",status=~\"200\"}[1m]))",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Error Requests",
   "type": "timeseries",
   "description": "This panel shows the total number of 40x and 50x error requests per service.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by (container, status) (rate(flask_http_request_duration_seconds_count{container=~\"backend|frontend\",status=~\"(^40\\\\d)\"}[1m]))",
     "legendFormat": "{{ container }} (40x)"
    },
    {
     "expr": "count by (container, status) (rate(flask_http_request_duration_seconds_count{container=~\"backend|frontend\",status=~\"(^50\\\\d)\"}[1m]))",
     "legendFormat": "{{ container }} (50x)"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "description": "This panel shows the average response time successful requests (status 200) per service.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(rate(flask_http_request_duration_seconds_sum{container=~\"backend\",status=\"200\"}[1m])) / sum(rate(flask_http_request_duration_seconds_count{container=~\"backend\",status=\"200\"}[1m]))) * 1000\n",
     "legendFormat": "backend"
    },
    {
     "expr": "(sum(rate(flask_http_request_duration_seconds_sum{container=~\"frontend\",status=\"200\"}[1m])) / sum(rate(flask_http_request_duration_seconds_count{container=~\"frontend\",status=\"200\"}[1m]))) * 1000\n",
     "legendFormat": "frontend"
    }
   ]
  },
  {
   "title": "Average Memory",
   "type": "timeseries",
   "description": "This panel shows the average memory used by each service.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"default\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"default\", workload_type=\"deployment\"}\n) by (workload, workload_type) / 1048576",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  {
   "title": "Average CPU Used",
   "type": "timeseries",
   "description": "This panel shows the average CPU used by each service.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(\n  node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"default\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"default\", workload_type=\"deployment\"}\n) by (workload, workload_type)\n",
     "legendFormat": "{{workload}} "
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(irate(container_network_receive_packets_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"default\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"default\", workload=~\".+\", workload_type=\"deployment\"}) by (workload))",
     "legendFormat": "{{ workload }} - Received"
    },
    {
     "expr": "- (sum(irate(container_network_transmit_packets_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"default\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"default\", workload=~\".+\", workload_type=\"deployment\"}) by (workload))",
     "legendFormat": "{{ workload }} - Transmitted"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "description": "This panel displays information about all the traces generated by Jaeger.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "targets": [
    { "query": "c2053b9", "service": "jaeger-query" }
   ]
  }
 ]
}